### ISSUE TITLE
how to use dmps for latent diffusion model ?

### ISSUE THREAD

**Issue by lizhengwei1992** [mengxiangming/dmps#1]
As described in the paper : `other variants of DM can also be easily adapted within our method with proper modifications`, can I use DMPS with latent diffusion model ?

**Comment by mengxiangming** [comment]
This is a good question. 
Let us denote the pixel and latent vectors as x and z, respectively.  Recall that `our method focuses on linear inverse problems of the form y = Ax + n where x is modeled by a diffusion model`. Instead, if we use a latent diffusion model on z, rather than x, then our method still applies as long as we can obtain the likelihood score P(y|z), which is possible for some, if not all, forms of decoders x = D(z).
